sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-018
env:
  global:
    -
      # LTD_AWS_ID
      secure: Mzdr08oS0qQUJsyYjJNxrL+DgMoYHOnj3ou6BbMNF4xa3GbaudyTSvSRsbpA4ZYgb8+ne1SbciSdc6J9Yp5T7G8bfLfwxNKgwzIEjq1LfZYrXK+XDGjC59Qhyi0hv2Zj1doVAh3q1XbHP94po7i9GXJ9tfPLm7ZA1BktjnZVcxTdRK/pSrvPT/X3dl6juQeVvhbCM65cC2Mh8osXA91eBtJ2jaiiiSmSOaGYFbH9+H4PdcNMO6+5jlJhi9P87j2LE7536TEma0PrHnM91gU5JUY+YVpUsHqFMHWLltv8Ari4orb8ZG+FjsBDjHo9dZOIZLPO9os3fNMnxG5kVGnR9/3ZTU93pxlzoTBjRLK44nxVHeP7UUxZrWZqUhVYpxfH2ZpR9hGHnYSMURNWS+2Sn+QX13MWm+G0a2qeSLGJfVM6+fnCqs7pdLvF1oUIHF2oPLJd/zblNWFjxWW3XYIO4T0JFfxzfUexzqBykPTNEv0GCcWKEN4oRJ6HfBS6ij5Yjtl9bCRLu3kYud0DdYA98Zk5UwMPtisIpRxMl76T/HTKoc4uT0x9ChxxG5/VSzRZViho00vPiM8r2bg5WSXTlF0CuhUmHDntWdGTIEMEsZVS2hWasTo5POyuHT3RaYydlbGfvJPL7gtC7fWbkXCZxtbYloUStG+Nd7y9FK6aRIc=
    -
      # LTD_AWS_SECRET
      secure: N7kSVCRdT1/ERXUIMJPEK7mNT4ny4TzCrvTo1NSCHnNpvRZszZIscQcjIvPE2CHpKX5I2xJj6qwEuOhDgrYapso3kggE7SyWQaVDUYMhY3eqmo+8ORS8I8vQyYjfw3QqHXveuHYSrq40XsxjFGTuCJw5ym39ArLdiyHnMF9aHg0VwtuNI1uxOfFU1GbnEXKFJLZqlkfREwVfDVmURxSGD8qluguTDDV7r0/Z4MgEj0MYFSHhf4OTlrLim/MaebnjL1vllA08jRLBmtNAGysA95Y902+jctBXCpsJnsRRQ8yg7ngJzjhErMatz8BDlNxDx7sfJDvm2+mVVd+FiUspBjtEOqFE3Dl3Dtd5uwS7Bl4bdlJ+z+Dgc+8KvfDBm36fCFfrRo1Vx3qhyDSijjEXY9HGovYRAG1B7dm50TZFLWc5udaTRa3XOgDpNein7HmKuQ4QUNWCQYIOTM0b5Bi5SrKaStLJLPCLmYCF3gfXqsOrKuqCUzf5B+p6CcL+mJjdHk5FEMCkmVzfKAuxUK2WcLR5u5hXaL+OBQFKXMkZzHUlxRGNmTHt8EnI6aXDjSpnyxzz1L6T2vlGBlCs3qkQvVwuBTWuQpNdxao967W2sA8Ln37NToRMJ0V+bnmG4q/DdvNwiH9KRXAqVVcAd+xHFORYLgaicTkVswdmjskSW34=
    -
      # LTD_USERNAME
      secure: MqllzzStCgEt1t5eMVVCEQP9ggtPTRX2oPrMKdbUNRhBiHw3SeizDfIFJLc+DcaE0NT+d5LNmtJqbm1/q9wQfdyZ8XkIR741Rhd9bhpRzWdqUNF1BKwiuECqTrH9lJxy2wW0shEPs34Xc4U1CwXVA5eo3t2cU3UWLcPA9pR7tzdeqLn6ANuw4Gr/HQu5zX7Gg2IDHsJZ4PCJlCK37rmGwzm8QHUXDml3DEwMjpjrtSFoLjbB3rDQR62hcPw+A9dBd4N0+tGbkz3u3w5WVsohady7grah57AJ/uv6aa6zeGiIklhFd4zkJcApPyBH+FzqSsUU7vOeZFuvr9415BJquQwtPiAcIgFcXleFYfjlaqGwnEF9jrNCqy6e/S8pByN9xPttc5qM61W2SqgXxHl+CjmCLA8bRIsZGgEwr3O1Ux/KNmSHyW1GzHVPXMcpFBHlR5hTnf+dAC2guv7iWDh0Xw5siPBk5x8bSwvWNMifCot9n4hO+VlJ7V3sIFzlGxJLjKkMSPGZbad2PMDLBIUVO0pOnnvm4iOb4hM8QV0nfxcTDj/rl1WJmSAldDLw+OwDpKgDgmMIDayjr6rI+VValRmZRgZjqWth7ow3a8oHfanZAQuJalMmXuhaSjc3WKZe8FA2Pp9zixRSOvnAap2brXzi1mRiEHv0tbFsdPaEFv0=
    -
      # LTD_PASSWORD
      secure: XDUkQB1sxBMCb/4PEvFAt/X+vsPlc4LakvNIPaotJBlZniqcx3n861VqyI7s5PIuaB+zCWtjmFCfD3kTxD4BSR50au9n1LtetpnIpl+a6gW66Pb6vGYaOTDfem5p9okBOcv6pgx0eMa7Fh60balkJAVuL5Yegz4px37ukJjGQcAFYg5tx8xXLt7NPjl81GM9SwKUIB+i1/JlJcGKXSn0xIwxomA5sb1HXm32uS6noC0wUZNvHHx/6reCxAhYxi/xzaJq0SIaY3JdMNDQp3nkLNg246Q6syxCldAIkhl5FH1/LTWgfJSH8t7cqzfLE3Ti2G0w1ws+FbYvLER3jOp1O+mQ2T02Nkzmm7Xwcwn9UgjSTa58Ym47WWts0FmVoJ9ZPFhUwFKt1SImc3jPQnAMO97c8wEfKC6kT3Oh7mhedno8ER09mN7FYQTLVtYy5cNYXXGmKOsmVEuqV1fmLx4uBJWvHVXEOlejztGO/SXDg/In5lSO39kMBxRH/0EG3EgKbu5IYZigD3c2YzQTnVHPYRcHbABrAKy/YyQvwnawawdxxJXIDOQSocWFDAXc6qsW1XM0Ev0n0/q/SZpYdXQwv3piY1/UPyO/G7bbliAIU0S6DTKKRf2ygqBfBhvw/IL9Kk8h6K5zkIOvCy3rKvuxd+MXfDktukIVlINWr3YjGqQ=
